---
- name: Update server packages
  apt:
    upgrade: dist
    update_cache: yes
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Start Apache Service
  service:
    name: apache2
    state: started
  become: yes 
