---
- name: Install nginx
  apt:
    name: "{{ packagename }}"
    state: present
  become: yes

- name: copy  nginx configuration 
  template:
    src:  conf.j2 
    dest: /etc/nginx/nginx.conf
  notify: restart Nginx  
  become: yes

- name: nginx copy html file
  copy:
    src: index.html
    dest: /var/www/html
  become: yes
